PAGES = [
dict(slug='trailrunning-weekend-valencia', lang='nl',
 title='Trailrunning weekend Valencia | Trailrun retreat Sierra Calderona',
 desc='Trailrunning weekend bij Valencia: 3 dagen trailrunnen in de Sierra Calderona, villa met zwembad in Casinos, max. 6 lopers, luchthaventransfer inbegrepen. Vanaf €495 p.p.',
 crumb='Trailrunning weekend Valencia', teaser='Drie dagen trailrunnen in de bergen bij Valencia, in een kleine groep.',
 eyebrow='Trailrun retreat · Valencia, Spanje', h1='Trailrunning weekend in Valencia',
 lead='Drie dagen trailrunnen door de dennenbossen en over de bergpaden van de Sierra Calderona, met een villa met zwembad als thuisbasis. Kleine groep, geen prestatiedruk.',
 hero='trail-runner-forest.jpg', hero_alt='Trailrunner op een bospad in de Sierra Calderona bij Valencia',
 body=[
  ('facts',[('3 dagen','vrijdag t/m zondag'),('± 43 km','verdeeld over 3 trails'),('max. 6','lopers per weekend'),('v.a. €495','p.p., alles verzorgd')]),
  ('h2','Trailrunnen bij Valencia, maar dan in de bergen'),
  ('p','Valencia kennen de meeste mensen van de stad, het strand en de paella. Maar op een klein uur rijden van de kust begint een heel ander Valencia: het bergachtige binnenland. Daar ligt de <strong>Sierra Calderona</strong>, een natuurpark vol dennenbossen, rode zandsteenrotsen, kloven en uitzichtpunten. Precies daar organiseert Wildcore Retreats zijn <strong>trailrunning weekend</strong>.'),
  ('p','Het weekend is bedoeld voor lopers die de natuur willen beleven in plaats van tijden willen verbeteren. We lopen op gevoel, stoppen waar het mooi is en blijven als groep bij elkaar. Wandelen op de steile stukken mag altijd.'),
  ('h2','Voor wie is dit trailrun weekend?'),
  ('p','Voor sportieve mensen vanaf 18 jaar die al wat hardlopen en de stap naar de trails willen zetten, of die gewoon een mooi, verzorgd trailrun weekend in Spanje zoeken. Trailervaring is niet nodig. Wel vragen we dat je <strong>minimaal anderhalf uur rustig kunt hardlopen</strong>. Heb je dat, dan kun je de routes aan, ook de lange zaterdag.'),
  ('p','Je komt alleen of met z\'n tweeën, allebei prima. De groep bestaat uit maximaal zes deelnemers, zodat er aandacht is voor iedereen.'),
  ('routes','Routes kunnen worden aangepast vanwege weer, bosbrandgevaar of veiligheid.'),
  ('h2','Een villa met zwembad als basis'),
  ('p','Je slaapt niet in een hotel maar in <strong>Villa El Pinar</strong>, een vrijstaande villa bij het dorp Casinos, midden in het groen en met uitzicht op de bergen. Na de trail duik je het zwembad in, lees je een boek op het terras of praat je na met de groep. Ontbijt, lunch en de gezamenlijke diners zijn inbegrepen, net als de transfers naar de startpunten.'),
  ('img','pool-sunset.jpg','Zwembad van Villa El Pinar bij zonsondergang','Na de trail: zwembad en rust in Villa El Pinar, bij Casinos.'),
  ('h2','Wat is er inbegrepen?'),
  ('ul',['Verblijf in Villa El Pinar (gedeelde tweepersoonskamer of glampingtent)','2x ontbijt, 3x lunch en 2x diner, plus koffie, thee en water','Luchthavenvervoer van en naar Valencia Airport','Transfers naar de startpunten van de trails','Begeleiding tijdens alle trailruns door gastheer Maurizio Salazar, sport- en shiatsutherapeut']),
  ('p','Niet inbegrepen: je vlucht naar Valencia en je reisverzekering (die is wel verplicht).'),
  ('h2','Wat neem je mee?'),
  ('ul',['Trailschoenen met goed profiel (liefst al ingelopen)','Een hardloopvest of kleine rugzak met plek voor water (±1,5 liter op zaterdag)','Een licht windjack: in de ochtend en op de toppen kan het fris zijn','Petje, zonnebril en zonnebrand, ook in de winter','Zwemspullen voor het zwembad van de villa']),
  ('dates','Trailrun'),
  ('h2','Waarom trailrunnen bij Valencia in de winter?'),
  ('p','De weekenden vinden plaats van november tot en met maart. In die maanden is het in Nederland en België vaak nat, donker en koud, terwijl het in het binnenland van Valencia overdag meestal aangenaam is om te lopen. In de zomer is het er juist te heet voor lange trails. Een trailrun weekend in de winter geeft je dus zon, droge paden en lange uitzichten, op een paar uur vliegen van huis.'),
 ],
 faq=[
  ('Moet ik ervaring hebben met trailrunnen?','Nee. Ervaring op de trail is niet nodig. Wel vragen we dat je minimaal anderhalf uur rustig kunt hardlopen. Op steile stukken wandelen we gewoon, en we blijven als groep bij elkaar.'),
  ('Hoe kom ik bij het trailrun weekend?','Je vliegt zelf naar Valencia Airport. Op vrijdag rond 13:00 uur halen we de groep op en rijden we samen naar de villa bij Casinos. Op zondagmiddag brengen we je terug naar het vliegveld.'),
  ('Wat kost een trailrunning weekend in Valencia?','De eerste editie (6–8 november 2026) kost €495 p.p. als introductieprijs. Daarna €595 p.p. Verblijf, maaltijden, luchthaventransfer en begeleiding zijn inbegrepen.'),
  ('Hoeveel lopers doen er mee?','Maximaal zes. Bij minder dan vier aanmeldingen gaat een weekend niet door; dat hoor je uiterlijk vier weken van tevoren, zodat je pas daarna je vlucht hoeft te boeken.'),
 ],
 related=['trailrunning-vakantie-spanje','trailrunning-wandelen-casinos','natuur-valencia-binnenland','wandelweekend-valencia']),

dict(slug='wandelweekend-valencia', lang='nl',
 title='Wandelweekend Valencia | Hiking weekend in de Sierra Calderona',
 desc='Wandelweekend of hiking weekend bij Valencia: 3 dagen hiken in natuurpark Sierra Calderona, villa met zwembad, max. 6 deelnemers, alles verzorgd. €595 p.p.',
 crumb='Wandelweekend Valencia', teaser='Drie dagen hiken in de natuur bij Valencia, met villa en zwembad.',
 eyebrow='Hike weekend · Valencia, Spanje', h1='Wandelweekend in Valencia: hiken in de Sierra Calderona',
 lead='Een verzorgd hiking weekend in de natuur van het Valenciaanse binnenland. Drie dagen wandelen door dennenbossen, langs kloven en uitzichtpunten, met een villa met zwembad als thuisbasis.',
 hero='valley-view.jpg', hero_alt='Uitzicht over een vallei in de Sierra Calderona bij Valencia',
 body=[
  ('facts',[('3 dagen','vrijdag t/m zondag'),('max. 6','wandelaars per weekend'),('€595','p.p., alles verzorgd'),('nov – mrt','de beste wandelmaanden')]),
  ('h2','Wandelen in Valencia, weg van de drukte'),
  ('p','Wie aan Valencia denkt, denkt aan de stad en de stranden. Maar het mooiste wandelgebied ligt in het binnenland: het natuurpark <strong>Sierra Calderona</strong>, met dennenbossen, rode zandsteenrotsen, oude paden en uitzichten over de valleien. Op heldere dagen kijk je vanaf de hogere punten tot aan de Middellandse Zee.'),
  ('p','Tijdens het <strong>wandelweekend van Wildcore Retreats</strong> hoef je zelf niets te regelen. Je wordt opgehaald op het vliegveld, slaapt in een villa met zwembad, eet samen en wandelt elke dag een andere route met begeleiding. Het is geen tocht waarbij het om snelheid gaat, maar een weekend om buiten te zijn en tot rust te komen.'),
  ('h2','Voor wie is het hikeweekend?'),
  ('p','Voor iedereen vanaf 18 jaar die graag wandelt en een goede basisconditie heeft. Je moet <strong>minimaal drie uur op heuvelachtig terrein kunnen wandelen</strong>. Je hoeft geen ervaren bergwandelaar te zijn. Je kiest vooraf voor het hikeweekend, dus je loopt het hele weekend met een groep die in hetzelfde tempo wandelt.'),
  ('routes','Het hikeweekend volgt dezelfde opbouw in hetzelfde gebied, in wandeltempo. Afstanden en routes kunnen per editie wijzigen door weer, bosbrandgevaar of veiligheid. Vraag gerust naar de details.'),
  ('img','waterfall-steps.jpg','Wandelpad met trappen langs een waterval in de Sierra Calderona','Op zondag wandel je langs kloven en watervallen.'),
  ('h2','Een wandelvakantie van een weekend, volledig verzorgd'),
  ('p','Een lang weekend is genoeg om echt even weg te zijn. Je vliegt op vrijdagochtend naar Valencia en bent zondagavond weer thuis. Daartussen hoef je aan niets te denken:'),
  ('ul',['Verblijf in Villa El Pinar bij Casinos: kamer of glampingtent tussen de pijnbomen','Ontbijt, lunch (ook onderweg in de natuur) en gezamenlijke diners','Luchthavenvervoer van en naar Valencia Airport','Vervoer naar de startpunten van de wandelingen','Begeleiding door gastheer Maurizio Salazar, die een deel van het jaar in Casinos woont']),
  ('p','Wil je er een langere wandelvakantie van maken? Kom een dag eerder en ontdek eerst de stad Valencia op eigen houtje.'),
  ('dates','Hike'),
  ('h2','Wat neem je mee voor het hiking weekend?'),
  ('ul',['Stevige wandelschoenen of trailschoenen met goed profiel','Een dagrugzak met ruimte voor water en lunch','Laagjes kleding: ochtenden en avonden kunnen fris zijn, overdag is het vaak zonnig','Zonnebrand, pet en zonnebril','Zwemspullen voor het zwembad']),
 ],
 faq=[
  ('Is het wandelweekend geschikt voor beginners?','Ja, als je een goede basisconditie hebt. Je moet minimaal drie uur op heuvelachtig terrein kunnen wandelen. Ervaring met bergwandelen is niet nodig.'),
  ('Wanneer is het volgende hiking weekend in Valencia?','De hikeweekenden zijn op 11–13 december 2026 en 5–7 maart 2027. Kijk op de homepage voor de actuele beschikbaarheid.'),
  ('Wat kost het wandelweekend?','€595 per persoon, inclusief verblijf, alle maaltijden tijdens het weekend, luchthaventransfer en begeleiding. Je vlucht en reisverzekering regel je zelf.'),
  ('Kan ik alleen meedoen?','Zeker. Veel mensen komen alleen. Met maximaal zes deelnemers leer je elkaar snel kennen.'),
 ],
 related=['wandelweekend-spanje','natuur-valencia-binnenland','trailrunning-wandelen-casinos','actieve-vakantie-valencia']),

dict(slug='trailrunning-vakantie-spanje', lang='nl',
 title='Trailrunning vakantie Spanje | Trailrun retreat & weekend',
 desc='Trailrunning vakantie in Spanje? Een kleinschalige trailrun retreat bij Valencia: 3 dagen trails in de Sierra Calderona, villa met zwembad, max. 6 lopers. Vanaf €495.',
 crumb='Trailrunning vakantie Spanje', teaser='Waarom een trailrun retreat in Spanje, en waarom klein beter is.',
 eyebrow='Trailrun retreat · Spanje', h1='Trailrunning vakantie in Spanje: een kleinschalige trailrun retreat',
 lead='Zon, droge paden en bergen op een paar uur vliegen van huis. Een trailrunning weekend in Spanje, bij Valencia, voor lopers die willen genieten in plaats van presteren.',
 hero='trail-descent-autumn.jpg', hero_alt='Trailrunners dalen af over een bergpad in de herfst in Spanje',
 body=[
  ('h2','Waarom Spanje voor een trailrun vakantie?'),
  ('p','Spanje is een van de fijnste landen in Europa om te trailrunnen. Er zijn bergen in bijna elke regio, veel paden zijn goed begaanbaar en het weer is een groot deel van het jaar droog. Vooral in de winter, als het in Nederland en België nat en donker is, kun je in Oost-Spanje nog heerlijk buiten lopen.'),
  ('p','De regio <strong>Valencia</strong> is daarbij extra handig: er zijn veel directe vluchten naar Valencia Airport, en vanaf daar ben je snel in de bergen. Wildcore Retreats organiseert er trailrunning weekenden in het natuurpark Sierra Calderona, vlak bij het dorp Casinos.'),
  ('h2','Een retreat, geen trainingskamp'),
  ('p','Veel trailrunreizen zijn trainingskampen: grote groepen, strakke schema\'s en veel kilometers. Een <strong>trailrun retreat</strong> bij Wildcore is anders. Het gaat om het beleven van de natuur, om rust en om samen lopen. Onze belofte is simpel: <em>niet presteren, maar beleven</em>.'),
  ('ul',['<strong>Kleine groep:</strong> maximaal zes deelnemers, zodat iedereen aandacht krijgt','<strong>Samen:</strong> we blijven als groep bij elkaar en stoppen waar het mooi is','<strong>Rust:</strong> na de trail is er het zwembad, het terras en goed eten','<strong>Alles verzorgd:</strong> van luchthaventransfer tot maaltijden en begeleiding']),
  ('h2','Een sportretreat van één weekend'),
  ('p','Niet iedereen kan een week vrij nemen. Daarom duurt het retreat van vrijdag tot en met zondag. Je vliegt vrijdagochtend naar Valencia, loopt ’s middags al je eerste trail en bent zondagavond weer thuis. In die drie dagen loop je ongeveer 43 kilometer, verdeeld over drie routes met elk een eigen karakter.'),
  ('routes',''),
  ('h2','Welk niveau heb je nodig?'),
  ('p','Je hoeft geen ervaren trailrunner te zijn. Het weekend is geschikt voor iedereen die <strong>minimaal anderhalf uur rustig kan hardlopen</strong>. Is dat nog een stap te ver? Dan is het <a href="/wandelweekend-spanje/">hikeweekend</a> misschien iets voor jou: hetzelfde gebied en dezelfde villa, maar in wandeltempo.'),
  ('img','mountain-steps-trail.jpg','Trailpad met stenen treden door de bergen van de Sierra Calderona','Afwisselende paden in de Sierra Calderona: bos, rotsen en uitzichten.'),
  ('dates','Trailrun'),
  ('h2','Trailrun weekend Spanje: wat kost het?'),
  ('p','De eerste editie van november 2026 kost <strong>€495 p.p.</strong> (introductieprijs). Daarna kost een trailrunweekend <strong>€595 p.p.</strong> Daarvoor krijg je twee nachten in een villa met zwembad, alle maaltijden tijdens het weekend, de luchthaventransfer, alle transfers naar de trails en begeleiding onderweg. Je vlucht naar Valencia boek je zelf, pas nadat vier weken voor vertrek vaststaat dat het weekend doorgaat.'),
 ],
 faq=[
  ('Wat is het verschil tussen een trailrun retreat en een trailrun kamp?','Een kamp draait vaak om training en kilometers. Deze retreat draait om beleven: een kleine groep, een rustig tempo, tijd voor uitzichten en ontspanning in een villa met zwembad.'),
  ('Wanneer is de beste tijd voor een trailrunning vakantie in Spanje?','In het oosten van Spanje zijn de herfst, winter en het vroege voorjaar ideaal. In de zomer is het vaak te heet voor lange trails. Onze trailrunweekenden zijn in november en januari.'),
  ('Waar in Spanje vindt de retreat plaats?','In de Sierra Calderona, in het binnenland van de provincie Valencia. De villa ligt in El Pinar, bij het dorp Casinos.'),
  ('Kan ik een vriend meenemen die liever wandelt?','Elk weekend is óf een trailrunweekend óf een hikeweekend, zodat de hele groep hetzelfde tempo heeft. Een wandelaar kan het beste een hikeweekend kiezen.'),
 ],
 related=['trailrunning-weekend-valencia','wandelweekend-spanje','actieve-vakantie-valencia','natuur-valencia-binnenland']),

dict(slug='wandelweekend-spanje', lang='nl',
 title='Wandelweekend Spanje | Hiking & outdoor weekend bij Valencia',
 desc='Een wandelweekend in Spanje zonder zelf iets te regelen: 3 dagen hiken in de Sierra Calderona bij Valencia, villa met zwembad, max. 6 deelnemers. Outdoor weekend vanaf €595.',
 crumb='Wandelweekend Spanje', teaser='Een verzorgd hiking- en outdoor weekend in Spanje, van vrijdag tot zondag.',
 eyebrow='Hiking weekend · Spanje', h1='Wandelweekend in Spanje: drie dagen hiken bij Valencia',
 lead='Even weg, de natuur in, zonder dat je een hele week vrij hoeft te nemen. Een outdoor weekend in Spanje met wandelen, goed eten en een villa met zwembad.',
 hero='ruins-viewpoint.jpg', hero_alt='Uitzichtpunt bij oude ruïnes in de bergen bij Valencia',
 body=[
  ('h2','Een hiking weekend in Spanje, volledig verzorgd'),
  ('p','Een wandelvakantie in Spanje plannen kost tijd: routes zoeken, accommodatie boeken, vervoer regelen. Bij het <strong>hiking weekend van Wildcore Retreats</strong> is dat allemaal geregeld. Je boekt een vlucht naar Valencia, en wij doen de rest.'),
  ('p','Het weekend speelt zich af in de <strong>Sierra Calderona</strong>, een beschermd natuurpark in het binnenland van Valencia. Het is een gebied met dennenbossen, kurkeiken, rode zandsteenrotsen, kloven en oude paden, en met uitzichten over het landschap tot aan de zee.'),
  ('h2','Zo ziet het outdoor weekend eruit'),
  ('ul',['<strong>Vrijdag:</strong> ophalen op Valencia Airport rond 13:00, lunch in de villa, een korte kennismakingstocht rond Casinos en een gezamenlijk diner','<strong>Zaterdag:</strong> de lange dag door de Sierra Calderona, met lunch onderweg in de natuur. \'s Middags zwembad en terras','<strong>Zondag:</strong> een rustigere route langs kloven en watervallen, lunch op het terras en de transfer terug naar het vliegveld']),
  ('routes','Het hikeweekend volgt dezelfde opbouw in wandeltempo. Afstanden kunnen per editie wijzigen door weer, bosbrandgevaar of veiligheid.'),
  ('h2','Waarom een wandelweekend in de winter?'),
  ('p','De hikeweekenden zijn in december en maart. Dan is het in het binnenland van Valencia overdag meestal zonnig en zacht genoeg om lekker te wandelen, terwijl het in de zomer te heet is om lang te lopen. Zo krijg je in de donkerste maanden van het jaar een paar dagen licht, zon en frisse berglucht.'),
  ('img','canyon-cliffs.jpg','Rotswanden van een kloof in de Sierra Calderona','Kloven, rotswanden en dennenbos: het landschap van de Sierra Calderona.'),
  ('h2','Klein, persoonlijk en zonder haast'),
  ('p','Er doen maximaal <strong>zes wandelaars</strong> mee. Dat maakt het weekend persoonlijk: je leert elkaar kennen, er is aandacht voor iedereen en er is tijd om stil te staan bij een uitzicht. Je gastheer is Maurizio Salazar, sport- en shiatsutherapeut, die een deel van het jaar in Casinos woont en de omgeving goed kent.'),
  ('p','Voor wie: iedereen vanaf 18 jaar die <strong>minimaal drie uur op heuvelachtig terrein kan wandelen</strong>. Je hoeft geen ervaren bergwandelaar te zijn.'),
  ('dates','Hike'),
 ],
 faq=[
  ('Hoe lang duurt het wandelweekend?','Van vrijdagmiddag tot zondagmiddag: drie dagen wandelen en twee nachten in de villa. Je hebt aan een lang weekend genoeg.'),
  ('Waar vlieg ik naartoe?','Naar Valencia Airport. Daar halen we de groep op vrijdag rond 13:00 op. Op zondagmiddag brengen we je terug.'),
  ('Wat kost een wandelweekend in Spanje bij Wildcore?','€595 p.p., inclusief verblijf, maaltijden, luchthaventransfer, vervoer naar de routes en begeleiding.'),
  ('Wat als het weekend niet doorgaat?','Er zijn minimaal vier deelnemers nodig. Uiterlijk vier weken voor vertrek hoor je of het doorgaat. Annuleert de organisatie, dan krijg je de volledige reissom terug.'),
 ],
 related=['wandelweekend-valencia','natuur-valencia-binnenland','actieve-vakantie-valencia','trailrunning-vakantie-spanje']),
]
