PAGES = [
dict(slug='trailrunning-wandelen-casinos', lang='nl',
 title='Trailrunning, hiking & wandelen in Casinos (Valencia)',
 desc='Trailrunnen, hiken of wandelen rond Casinos, Valencia? Ontdek de paden aan de voet van de Sierra Calderona en loop mee met een kleinschalig weekend vanuit Villa El Pinar.',
 crumb='Casinos, Valencia', teaser='Het dorp aan de voet van de Sierra Calderona waar ons weekend begint.',
 eyebrow='Casinos · Valencia binnenland', h1='Trailrunning, hiking en wandelen in Casinos, Valencia',
 lead='Casinos is een rustig dorp in het binnenland van Valencia, omringd door boomgaarden en heuvels. Het is de thuisbasis van Wildcore Retreats en het startpunt van onze trails en hikes.',
 hero='villa-exterior.jpg', hero_alt='Villa El Pinar bij Casinos met uitzicht op de bergen',
 body=[
  ('h2','Waar ligt Casinos?'),
  ('p','Casinos ligt ten noordwesten van de stad Valencia, in de streek Camp de Túria. Het is een authentiek Spaans dorp, bekend om zijn <em>turrón</em> (Spaanse nougat) en omringd door sinaasappel- en amandelboomgaarden. In het voorjaar ruikt het er naar oranjebloesem, in de winter hangen de bomen vol sinaasappels.'),
  ('p','Vlak bij het dorp ligt de rustige urbanisatie <strong>El Pinar</strong>, tussen de pijnbomen. Daar staat Villa El Pinar, de villa waar deelnemers van onze weekenden verblijven. Vanaf Valencia Airport is het ongeveer een half uur tot drie kwartier rijden; die transfer is bij het weekend inbegrepen.'),
  ('h2','Trailrunnen rond Casinos'),
  ('p','Rond Casinos vind je brede bospaden, smalle paadjes door de dennen en glooiende heuvels. Het terrein is afwisselend maar goed te belopen, en daarom ideaal om kennis te maken met trailrunning. Iets verder naar het oosten begint het echte bergwerk van de <strong>Sierra Calderona</strong>, met meer hoogtemeters en uitzichten over de valleien.'),
  ('p','Het trailrunweekend van Wildcore begint op vrijdagmiddag met de <strong>Casinos Discovery Loop</strong>: 8 km en ongeveer 180 hoogtemeters, direct vanuit de omgeving van de villa. Een rustige eerste loop om de benen los te maken en de groep te leren kennen.'),
  ('h2','Hiking en wandelen bij Casinos'),
  ('p','Ook voor wandelaars is Casinos een fijne uitvalsbasis. De omgeving is stil, je ziet weinig andere mensen en de natuurparken liggen dichtbij. Tijdens het <a href="/wandelweekend-valencia/">hikeweekend</a> wandel je dezelfde gebieden in wandeltempo, met lunch onderweg en \'s middags tijd voor het zwembad.'),
  ('img','villa-flowers.jpg','Tuin met bloemen bij Villa El Pinar in Casinos','Villa El Pinar: tuin, terras en zwembad, midden in het groen bij Casinos.'),
  ('routes','Alle routes starten in of vlak bij Casinos; op zaterdag en zondag brengen we je met de auto naar het startpunt.'),
  ('h2','Waarom Casinos als uitvalsbasis?'),
  ('ul',['<strong>Rust:</strong> geen toeristische drukte, wel echte Spaanse dorpssfeer','<strong>Natuur dichtbij:</strong> bospaden vanaf de deur en de Sierra Calderona op korte afstand','<strong>Bereikbaar:</strong> dichtbij Valencia Airport, met een gezamenlijke transfer','<strong>Een thuisbasis:</strong> een villa met zwembad, terras en tuin in plaats van een hotel']),
  ('dates',None),
 ],
 faq=[
  ('Hoe ver is Casinos van Valencia?','Casinos ligt in het binnenland ten noordwesten van Valencia. Vanaf Valencia Airport rijd je er ongeveer een half uur tot drie kwartier naartoe. Bij het weekend is de transfer inbegrepen.'),
  ('Kun je rond Casinos goed trailrunnen?','Ja. Er zijn bospaden en heuvels direct rond het dorp, en de bergpaden van de Sierra Calderona liggen dichtbij. Ideaal voor zowel beginnende als ervaren trailrunners.'),
  ('Waar verblijf je tijdens het weekend?','In Villa El Pinar, een vrijstaande villa met zwembad in de urbanisatie El Pinar bij Casinos. Je kunt kiezen voor een gedeelde tweepersoonskamer of een glampingtent tussen de pijnbomen.'),
 ],
 related=['natuur-valencia-binnenland','trailrunning-weekend-valencia','wandelweekend-valencia','actieve-vakantie-valencia']),

dict(slug='natuur-valencia-binnenland', lang='nl',
 title='Natuur, wandelen & trailrunning in het binnenland van Valencia',
 desc='Ontdek de natuur van het Valenciaanse binnenland: wandelen en trailrunnen in de Sierra Calderona, dennenbossen, kloven en uitzichten. Plus tips voor een natuurvakantie bij Valencia.',
 crumb='Natuur in het binnenland van Valencia', teaser='Wandelen en trailrunnen in de bergen achter de stad Valencia.',
 eyebrow='Natuurgids · Valencia binnenland', h1='Wandelen, trailrunnen en natuur in het binnenland van Valencia',
 lead='Achter de stad en de stranden ligt een groen, bergachtig Valencia dat veel bezoekers nooit zien. Een gids voor wie daar wil wandelen, hardlopen of gewoon de natuur in wil.',
 hero='river-canyon.jpg', hero_alt='Rivier door een kloof in het binnenland van Valencia',
 body=[
  ('h2','Het andere Valencia'),
  ('p','De provincie Valencia is veel meer dan de stad aan zee. Rij een half uur landinwaarts en het landschap verandert: boomgaarden maken plaats voor heuvels, en heuvels voor bergen met dennenbossen, kloven en riviertjes. Dit binnenland is stil, groen en perfect voor wie wil <strong>wandelen</strong> of <strong>trailrunnen</strong>.'),
  ('h2','De Sierra Calderona: het groene hart'),
  ('p','Het bekendste natuurgebied vlak bij de stad is het <strong>Parc Natural de la Serra Calderona</strong>. Het bergmassief ligt op de grens van de provincies Valencia en Castellón en is sinds 2002 een beschermd natuurpark. Je vindt er:'),
  ('ul',['Uitgestrekte dennenbossen en kurkeiken','Rode zandsteenrotsen en kalksteen','Kloven, bronnen en kleine watervallen, zoals rond Rebalsadors','Uitzichtpunten waar je op heldere dagen tot aan de Middellandse Zee kijkt','Een netwerk van paden, van brede bosweg tot smal bergpad']),
  ('img','canyon-cliffs.jpg','Rotsachtige kloof in de Sierra Calderona','De Sierra Calderona: rotsen, kloven en dennenbos.'),
  ('h2','Wandelen in het binnenland van Valencia'),
  ('p','Voor wandelaars is de Sierra Calderona een van de mooiste gebieden in de regio. De paden zijn afwisselend, de hoogteverschillen zijn goed te doen en je hebt vaak het gevoel dat je het gebied voor jezelf hebt. Het beste wandelseizoen loopt van oktober tot en met april; in de zomer is het overdag vaak te warm om lang te lopen.'),
  ('h2','Trailrunning in het Valenciaanse binnenland'),
  ('p','Ook voor trailrunners is dit gebied een ontdekking. Snelle bospaden, technische afdalingen en klimmetjes naar uitzichtpunten wisselen elkaar af. Wie er voor het eerst loopt, heeft wel baat bij iemand die de weg kent: paden zijn niet altijd goed aangegeven en water onderweg is schaars.'),
  ('h2','Een natuurvakantie bij Valencia, zonder zelf te plannen'),
  ('p','Wil je dit gebied leren kennen zonder zelf routes uit te zoeken? Wildcore Retreats organiseert kleinschalige <a href="/trailrunning-weekend-valencia/">trailrunweekenden</a> en <a href="/wandelweekend-valencia/">hikeweekenden</a> in de Sierra Calderona, met een villa met zwembad bij Casinos als thuisbasis. Drie dagen natuur, drie routes, maximaal zes deelnemers.'),
  ('routes',''),
  ('dates',None),
 ],
 faq=[
  ('Wat is het mooiste natuurgebied bij Valencia?','Er zijn er meerdere, maar de Sierra Calderona is voor veel wandelaars en trailrunners favoriet: dichtbij de stad, groen, bergachtig en met veel paden.'),
  ('Wanneer kun je het beste wandelen in het binnenland van Valencia?','Van oktober tot en met april. Dan is het overdag meestal zonnig en aangenaam. In de zomer is het vaak te heet voor lange tochten.'),
  ('Kun je in het binnenland van Valencia trailrunnen?','Ja, het gebied is ideaal. De Sierra Calderona heeft bospaden, bergpaden en flinke klimmen. Onze trailrunweekenden laten je in drie dagen de mooiste kanten zien.'),
 ],
 related=['trailrunning-wandelen-casinos','wandelweekend-valencia','trailrunning-weekend-valencia','actieve-vakantie-valencia']),

dict(slug='actieve-vakantie-valencia', lang='nl',
 title='Actieve vakantie Valencia | Sportieve natuurvakantie & outdoor',
 desc='Een actieve of sportieve vakantie in Valencia? Combineer de stad met een outdoor weekend trailrunnen of hiken in de natuur van de Sierra Calderona. Klein, verzorgd, vanaf €495.',
 crumb='Actieve vakantie Valencia', teaser='Stad, natuur en sport: een actieve vakantie in de regio Valencia.',
 eyebrow='Actief & outdoor · Valencia, Spanje', h1='Actieve vakantie in Valencia: sport, natuur en rust',
 lead='Valencia is een van de fijnste bestemmingen in Spanje voor een sportieve vakantie. Combineer een paar dagen in de stad met een outdoor weekend in de bergen.',
 hero='valley-view.jpg', hero_alt='Groene vallei in de bergen van de regio Valencia',
 body=[
  ('h2','Waarom Valencia voor een actieve vakantie?'),
  ('p','Valencia heeft alles voor een actieve vakantie: veel zon, een milde winter, een levendige stad en, op korte afstand, bergen en natuurparken. Veel mensen blijven in de stad of aan het strand. Maar wie net iets verder kijkt, vindt in het binnenland een groene, rustige wereld om te wandelen en te trailrunnen.'),
  ('h2','Een sportieve vakantie in drie dagen'),
  ('p','Wildcore Retreats organiseert kleinschalige <strong>outdoor weekenden</strong> in de Sierra Calderona, in het binnenland van Valencia. Je kiest vooraf tussen:'),
  ('ul',['<a href="/trailrunning-weekend-valencia/"><strong>Trailrunweekend</strong></a> voor wie minimaal anderhalf uur rustig kan hardlopen','<a href="/wandelweekend-valencia/"><strong>Hikeweekend</strong></a> voor wie minimaal drie uur op heuvelachtig terrein kan wandelen']),
  ('p','In beide gevallen verblijf je in een villa met zwembad bij Casinos, eet je samen, loop je elke dag een andere route en word je opgehaald en teruggebracht naar Valencia Airport. Maximaal zes deelnemers per weekend.'),
  ('routes',''),
  ('h2','Maak er een langere reis van'),
  ('p','Het weekend begint op vrijdag rond 13:00 op het vliegveld. Veel deelnemers komen een dag eerder, zodat ze eerst de stad kunnen ontdekken. Denk aan een fietstocht door de <em>Jardín del Turia</em>, het park in de oude rivierbedding, de oude binnenstad en de markthal, en natuurlijk een paella aan het einde van de dag. Na zo\'n stadsdag voelt de rust van de bergen extra goed.'),
  ('img','pool-sunset.jpg','Zwembad bij de villa in de bergen bij Valencia bij zonsondergang','Sport overdag, rust bij het zwembad in de middag.'),
  ('h2','Natuurvakantie of sportvakantie? Allebei'),
  ('p','Een actieve vakantie hoeft niet zwaar te zijn. Bij Wildcore draait het niet om prestaties maar om beleven: bewegen in de natuur, goed eten en tijd voor jezelf. Na de trail kun je aan het zwembad liggen, een boek lezen op het terras of samen napraten. <em>Niet presteren, maar beleven.</em>'),
  ('dates',None),
 ],
 faq=[
  ('Wat kun je actief doen in Valencia?','In de stad kun je fietsen door het Turia-park en hardlopen langs het strand. In het binnenland kun je wandelen, hiken en trailrunnen in natuurparken zoals de Sierra Calderona.'),
  ('Is een actieve vakantie in Valencia ook in de winter leuk?','Juist dan. Van november tot en met maart is het in de regio vaak zonnig en aangenaam om buiten te sporten, terwijl het in de zomer erg heet kan zijn.'),
  ('Kan ik het weekend combineren met een stedentrip?','Ja. Kom een dag eerder of blijf een dag langer in Valencia. De transfer van het weekend vertrekt vrijdag rond 13:00 vanaf Valencia Airport.'),
 ],
 related=['trailrunning-weekend-valencia','wandelweekend-valencia','natuur-valencia-binnenland','trailrunning-vakantie-spanje']),
]
