PAGES = [
dict(slug='en/trail-running-valencia', lang='en',
 title='Trail Running Valencia | Trail Running Retreat in Spain',
 desc='Trail running near Valencia, Spain: a 3-day trail running retreat in the Sierra Calderona with a villa and pool, max. 6 runners, airport transfer included. From €495.',
 crumb='Trail running Valencia', teaser='Three days of trail running in the mountains behind Valencia.',
 eyebrow='Trail running retreat · Valencia, Spain', h1='Trail running in Valencia: a small-group retreat in the Sierra Calderona',
 lead='Three days on pine-forest trails and mountain paths in the Sierra Calderona, with a villa and pool as your base. Small group, no pressure to perform.',
 hero='trail-runner-forest.jpg', hero_alt='Trail runner on a forest path in the Sierra Calderona near Valencia',
 body=[
  ('facts',[('3 days','Friday to Sunday'),('± 43 km','across 3 trails'),('max. 6','runners per weekend'),('from €495','pp, all-inclusive')]),
  ('h2','Trail running in Spain, just outside Valencia'),
  ('p','Most people know Valencia for its city, beaches and paella. But less than an hour inland there is a very different Valencia: the mountains. The <strong>Sierra Calderona Natural Park</strong> is full of pine forests, red sandstone, gorges and viewpoints, with trails for every level. That is where Wildcore Retreats runs its <strong>trail running weekends</strong>.'),
  ('p','This is a retreat, not a training camp. We run by feel, stop where it is beautiful and stay together as a group. Walking the steep bits is always fine. Our motto: <em>don\'t perform, experience</em>.'),
  ('h2','Who is it for?'),
  ('p','Anyone aged 18+ who can <strong>run easily for at least an hour and a half</strong>. No trail experience is needed. You can come alone or with a friend; groups are a maximum of six people, so everyone gets attention.'),
  ('routes','Routes may be adjusted for weather, wildfire risk or safety.'),
  ('h2','Your base: a villa with a pool'),
  ('p','You stay at <strong>Villa El Pinar</strong>, a detached villa near the village of Casinos, surrounded by greenery with views of the mountains. After the trail: a swim, the terrace, good food and good company. Or some time on your own, if you prefer.'),
  ('img','pool-sunset.jpg','Pool at Villa El Pinar at sunset','Villa El Pinar near Casinos: pool, terrace and mountain views.'),
  ('h2','What\'s included'),
  ('ul',['Two nights at Villa El Pinar (shared twin room or glamping tent)','2 breakfasts, 3 lunches and 2 dinners, plus coffee, tea and water','Transfer to and from Valencia Airport','Transport to all trailheads','Guidance on every run from host Maurizio Salazar, sports and shiatsu therapist']),
  ('p','Not included: your flight to Valencia and travel insurance (which is required).'),
  ('dates','Trail run'),
  ('h2','Why trail running in Valencia in winter?'),
  ('p','The weekends run from November to March. While northern Europe is wet and dark, inland Valencia usually offers pleasant running weather, dry trails and long views. Summer is too hot for long trail days, which makes winter the ideal season.'),
 ],
 faq=[
  ('Do I need trail running experience?','No. You just need to be able to run easily for at least 90 minutes. We walk the steep sections and stay together as a group.'),
  ('How do I get there?','Fly into Valencia Airport. We pick the group up on Friday around 1 pm and drive to the villa near Casinos. On Sunday afternoon we take you back to the airport.'),
  ('How much does the trail running retreat cost?','The first edition (6–8 November 2026) costs €495 pp as a launch price. After that it is €595 pp, including accommodation, meals, airport transfers and guidance.'),
  ('Is it in English?','Yes. Your host speaks Dutch, English and Spanish.'),
 ],
 related=['en/hiking-retreat-spain']),

dict(slug='en/hiking-retreat-spain', lang='en',
 title='Hiking Retreat Spain | Hiking Weekend in Valencia',
 desc='A small-group hiking retreat in Spain: 3 days hiking in the Sierra Calderona near Valencia, villa with pool, max. 6 people, meals and airport transfer included. €595 pp.',
 crumb='Hiking retreat Spain', teaser='A fully organised hiking weekend in the nature around Valencia.',
 eyebrow='Hiking retreat · Valencia, Spain', h1='Hiking retreat in Spain: a hiking weekend near Valencia',
 lead='Hiking in Spain without planning a thing. Three days of walking through pine forests, gorges and viewpoints in the Sierra Calderona, with a villa and pool to come home to.',
 hero='valley-view.jpg', hero_alt='View over a valley in the Sierra Calderona near Valencia',
 body=[
  ('facts',[('3 days','Friday to Sunday'),('max. 6','hikers per weekend'),('€595','pp, all-inclusive'),('Nov – Mar','best hiking season')]),
  ('h2','Hiking in Valencia: the mountains behind the city'),
  ('p','Valencia is best known for its city and beaches, but the best hiking is inland. The <strong>Sierra Calderona</strong>, a protected natural park since 2002, has pine and cork-oak forests, red sandstone rock, old paths and viewpoints where you can see all the way to the Mediterranean on a clear day.'),
  ('p','On a <strong>Wildcore hiking weekend</strong> everything is taken care of. We pick you up at the airport, you stay in a villa with a pool, we eat together and each day you hike a different route with a guide. It is not about speed. It is about being outside and slowing down.'),
  ('h2','Who is this hiking retreat for?'),
  ('p','Anyone aged 18+ in reasonable shape who can <strong>hike for at least three hours on hilly terrain</strong>. You do not need to be an experienced mountain hiker. Because each weekend is either a hiking or a trail running weekend, the whole group moves at the same pace.'),
  ('routes','The hiking weekend follows the same three-day structure in the same area, at walking pace. Distances may vary per edition due to weather, wildfire risk or safety. Feel free to ask for details.'),
  ('img','waterfall-steps.jpg','Stone steps along a waterfall in the Sierra Calderona','On Sunday you hike past gorges and waterfalls.'),
  ('h2','What\'s included'),
  ('ul',['Two nights at Villa El Pinar near Casinos (shared twin room or glamping tent)','Breakfasts, lunches (including out on the trail) and shared dinners','Transfer to and from Valencia Airport','Transport to the start of each hike','Guidance from host Maurizio Salazar, who lives part of the year in Casinos']),
  ('dates','Hike'),
  ('h2','Why a hiking weekend in winter?'),
  ('p','The hiking weekends take place in December and March, when inland Valencia is usually sunny and mild enough for comfortable hiking. In summer it is often too hot for long days on the trail. A long weekend is enough: fly in on Friday morning, be home on Sunday night.'),
 ],
 faq=[
  ('Is this hiking retreat suitable for beginners?','Yes, if you have a good base level of fitness and can hike for at least three hours on hilly terrain. No mountain experience needed.'),
  ('When are the next hiking weekends?','11–13 December 2026 and 5–7 March 2027. Check the homepage for current availability.'),
  ('Can I join on my own?','Absolutely. Many people come alone. With a maximum of six participants, you get to know each other quickly.'),
  ('What if the weekend does not go ahead?','A minimum of four participants is needed. You will know at least four weeks before departure, and if we cancel you get a full refund.'),
 ],
 related=['en/trail-running-valencia']),
]
